<a href="https://colab.research.google.com/github/jishma-shareena/google_crash_onML/blob/master/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Tutorial

It is a Python scientific computing package for 
  1. Matrix processing making use of GPUs
  1. Deep learning research 

Tensors can also be used on a GPU to accelarate computing.

In [0]:
import torch

#### Unitialized matrix

In [0]:
x = torch.empty(5, 3)
print(x)


tensor([[-1.0216e-06,  4.5602e-41, -1.0216e-06],
        [ 4.5602e-41,  4.3056e+21,  7.5554e+28],
        [ 1.7592e+22,  1.1729e-19,  1.2099e+25],
        [ 1.8611e+34,  6.3183e+28,  6.2691e+22],
        [ 4.7428e+30,  1.2106e+25,  4.3053e+21]])


#### Random Matrix

In [0]:
x = torch.randn(5,3)#uniformly distributed in [0,1]
print(x)

tensor([[ 0.6239,  0.2620,  0.8764],
        [ 1.4618,  0.5366, -0.0251],
        [-1.6157,  0.4294,  0.7818],
        [-0.4720, -0.3950, -0.4954],
        [-0.3928,  2.0235,  0.4930]])


In [0]:
x = torch.zeros(5,3,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [0]:
x = torch.ones(3,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [0]:
type(x)

torch.Tensor

Create a tensor directly from data

In [0]:
x = torch.Tensor([3,4.5])
print(x)

tensor([3.0000, 4.5000])


Create a tensor from existing data. These tensors will make use of the properties of the input tensor unless user provides other values

In [0]:
x = x.new_ones(5,3)
print(x)
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.1517, -0.0853,  0.4065],
        [ 1.3773, -1.6641,  0.0430],
        [ 0.2738, -1.1307,  0.6766],
        [-0.2649,  0.8793, -0.5621],
        [ 0.7955, -1.9364, -0.8007]])


Getting the shape and size of a tensor

In [0]:
print("Shape of the tensor is " , x.shape)
print("The shape of the tensor is ", x.size())

Shape of the tensor is  torch.Size([5, 3, 3])
The shape of the tensor is  torch.Size([5, 3, 3])


In [0]:
y = torch.randn_like(x,dtype=torch.float)
print(y)

tensor([[[ 0.8472,  0.6929, -0.5014],
         [ 0.3371, -1.4125,  0.4087],
         [-0.4707, -2.0441, -0.5349]],

        [[ 0.9428, -0.1110, -0.6216],
         [-1.7062,  1.1234, -0.4036],
         [ 0.3263, -0.2838,  1.0547]],

        [[ 0.5916,  0.7334, -0.3841],
         [ 0.5203,  2.2600,  0.5309],
         [-0.6211, -1.4453,  1.3032]],

        [[-0.1242, -1.1522, -0.2002],
         [-1.1971, -0.5217, -0.2505],
         [ 0.9902,  1.0225,  0.0947]],

        [[-1.3345, -0.1100,  0.9017],
         [-0.3070,  1.1676,  1.5907],
         [ 0.4221, -0.6543, -0.2466]]])


In [0]:
z = x+y 
z = torch.add(x,y)
y.add_(x)
print(z,y)

tensor([[[ 0.8472,  0.6929, -0.5014],
         [ 0.3371, -1.4125,  0.4087],
         [-0.4707, -2.0441, -0.5349]],

        [[ 0.9428, -0.1110, -0.6216],
         [-1.7062,  1.1234, -0.4036],
         [ 0.3263, -0.2838,  1.0547]],

        [[ 0.5916,  0.7334, -0.3841],
         [ 0.5203,  2.2600,  0.5309],
         [-0.6211, -1.4453,  1.3032]],

        [[-0.1242, -1.1522, -0.2002],
         [-1.1971, -0.5217, -0.2505],
         [ 0.9902,  1.0225,  0.0947]],

        [[-1.3345, -0.1100,  0.9017],
         [-0.3070,  1.1676,  1.5907],
         [ 0.4221, -0.6543, -0.2466]]]) tensor([[[ 0.8472,  0.6929, -0.5014],
         [ 0.3371, -1.4125,  0.4087],
         [-0.4707, -2.0441, -0.5349]],

        [[ 0.9428, -0.1110, -0.6216],
         [-1.7062,  1.1234, -0.4036],
         [ 0.3263, -0.2838,  1.0547]],

        [[ 0.5916,  0.7334, -0.3841],
         [ 0.5203,  2.2600,  0.5309],
         [-0.6211, -1.4453,  1.3032]],

        [[-0.1242, -1.1522, -0.2002],
         [-1.1971, -0.5217, -0.250

In [0]:
z1 = x*y
z2 = torch.mul(x,y)

Any operation that mutates a tensor in place is post-fixed with _ . For instance x.copy_(y) and x.t_() mutates x in-place

Slicing can be done as in numpy

In [0]:
import numpy as np
x = torch.from_numpy(np.arange(0,18)).view(2,3,3)
print(x)
print(x[0,1,1:]) # 0th row of the tensor x


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([4, 5])


In [0]:
x[:,0] #0th column of the tensor x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Reshape/resize a tensor. Use *view* to do that

In [0]:
x = torch.randn(4,5)
print(x.data)


tensor([[-0.2959, -0.4985, -0.4986,  1.5352, -0.9586],
        [-1.6423,  0.7660, -0.0837, -0.3631, -0.7907],
        [ 0.8572,  0.1982,  0.3890,  0.3143,  0.9958],
        [ 0.0283,  0.8481, -0.1592,  0.9283,  1.0917]])


print the first two rows and columns of x

In [0]:
print(x[:,[0,2,4]])

tensor([[-0.1627, -0.5796,  0.2582],
        [ 1.0682,  0.6438,  0.4083],
        [-0.4226,  1.0184,  1.4377],
        [ 0.7201,  0.7566,  1.3571]])


In [0]:
x = x.view(-1,5)
#print(x[10,0])

In [0]:
x = x.view(5,-1)

In [0]:
print(x)

tensor([[-0.1627, -1.5571, -0.5796, -1.6751],
        [ 0.2582,  1.0682,  0.9463,  0.6438],
        [-0.8692,  0.4083, -0.4226,  1.7094],
        [ 1.0184,  0.5408,  1.4377,  0.7201],
        [-0.5195,  0.7566,  0.1459,  1.3571]])


In case of one element tensor use item to extract the value of the tensor

In [0]:
x = torch.tensor(4)

In [0]:
print(x.item())

4


## Numpy Bridge

#### From tensor to numpy array

In [0]:
x = torch.tensor([[4,5],[5,6]])

In [0]:
x_numpy = x.numpy()

In [0]:
print(x_numpy)

[[4 5]
 [5 6]]


changing the value of the tensor will change the value of the numpy array also. they both point to the same location in memory

In [0]:
x = x.add_(1)
y = x+1
print(y)

tensor([[1.7041, 1.5015, 1.5014, 3.5352, 1.0414],
        [0.3577, 2.7660, 1.9163, 1.6369, 1.2093],
        [2.8572, 2.1982, 2.3890, 2.3143, 2.9958],
        [2.0283, 2.8481, 1.8408, 2.9283, 3.0917]])


#### From numpy to tensor

In [0]:
import numpy as np

a = np.ones((3,3))
a_torch = torch.from_numpy(a)
print(a_torch)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
np.add(a,1,out=a)
print(a,"\n",a_torch)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]] 
 tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], dtype=torch.float64)
